import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://mlhlpslhrvwjasbttghw.supabase.co';
const SERVICE_ROLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1saGxwc2xocnZ3amFzYnR0Z2h3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4OTUzNDU3NCwiZXhwIjoyMTA1MTEwNTc0fQ.YHeREZuf-1HjFx11LEB-76W0c3IFEH6I5r-K4mph5o4';

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);

// Raw brand-category mappings provided by user
const MAPPED_ROWS = [
  { brand: "AGARO", category: "After Shave" },
  { brand: "AIR KARPURE", category: "Air Freshner" },
  { brand: "AIR WICK", category: "Almond Oil" },
  { brand: "AJAY", category: "Aloevera Gel" },
  { brand: "AJMAL", category: "Antiseptic Liquid" },
  { brand: "ALPS GOODNESS", category: "Bath Brush" },
  { brand: "ALTON", category: "Bath Powder" },
  { brand: "AMBI PUR", category: "Bath Salt" },
  { brand: "ANIMATE", category: "Battery" },
  { brand: "ANOOS", category: "BB Cream" },
  { brand: "AQUALOGICA", category: "Bindi" },
  { brand: "ARATA", category: "Blackhead Remover" },
  { brand: "ARMAF", category: "Blusher" },
  { brand: "AROMA CARE", category: "Body Lotion" },
  { brand: "AROMA MAGIC", category: "Body Scrub" },
  { brand: "ASWINI", category: "Body Spray" },
  { brand: "AUREANA", category: "Body Wash" },
  { brand: "AURIC", category: "Body Wax" },
  { brand: "AVEENO", category: "Bottle" },
  { brand: "AXE", category: "Brush" },
  { brand: "AYOUTH VEDA", category: "Brush Cleaner" },
  { brand: "AYUR", category: "Cartridge" },
  { brand: "BABILA", category: "Castor Oil" },
  { brand: "BADZ PLAY", category: "Cleaner Flr / Toilt" },
  { brand: "BAJAJ", category: "Cleansing Milk" },
  { brand: "BANJARA", category: "Compact" },
  { brand: "BATH & BODY WORKS", category: "Concealer" },
  { brand: "BATISTE", category: "Conditioner" },
  { brand: "BBLUNT", category: "Cotton" },
  { brand: "BE BODYWISE", category: "Cotton Pads" },
  { brand: "BEARDO", category: "Cream" },
  { brand: "BEAUTE BLANC", category: "Deodrant" },
  { brand: "BEAUTE SECRETS", category: "Derma Roller" },
  { brand: "BEAUTY", category: "Developer" },
  { brand: "BEAUTY ZONE", category: "Diapers" },
  { brand: "BELLA VITA ORGANIC", category: "Ear Buds" },
  { brand: "BEURER BEAUTY", category: "Ear Plug" },
  { brand: "BIGEN", category: "Ear Ring" },
  { brand: "BILUMA", category: "Essential" },
  { brand: "BIO OIL", category: "Essential Oil" },
  { brand: "BIODERMA", category: "Eye Lash" },
  { brand: "BIOTIQUE", category: "Eye Lash Glue" },
  { brand: "BLUE HEAVEN", category: "Eye Shadow" },
  { brand: "BORO PLUS", category: "Eyebrow" },
  { brand: "BOROLINE", category: "Eyebrow Pencil" },
  { brand: "BRASIL CACAU PRO", category: "Eyelash Curler" },
  { brand: "BRUSHMAN", category: "Eyeliner" },
  { brand: "BRUT", category: "Eyeshadow" },
  { brand: "CAMAY", category: "Face Cream" },
  { brand: "CAMPURE", category: "Face Mask" },
  { brand: "CANDIO", category: "Face Mist" },
  { brand: "CARESMITH", category: "Face Pack" },
  { brand: "CERAVE", category: "Face Scrub" },
  { brand: "CETAPHIL", category: "Face Scrub" },
  { brand: "CHEMIST AT PLAY", category: "Face Serum" },
  { brand: "CHICCO", category: "Face Wash" },
  { brand: "CIGAR", category: "Facial Band" },
  { brand: "CLEAN & CLEAR", category: "Facial Kit" },
  { brand: "CLEAN AND DRY", category: "Fancy Item" },
  { brand: "CLEAR", category: "Foot Filer" },
  { brand: "CLINIC PLUS", category: "Foundation" },
  { brand: "CLOSEUP", category: "Freshner" },
  { brand: "COLGATE", category: "General Item" },
  { brand: "COLOR TREND", category: "Grooming" },
  { brand: "COLORESSENCE", category: "Hair Acc" },
  { brand: "COSRX", category: "Hair Brush" },
  { brand: "CURL UP", category: "Hair Color" },
  { brand: "CURLIN", category: "Hair Comb" },
  { brand: "DABUR", category: "Hair Cream" },
  { brand: "DE CONSTRUCT", category: "Hair Dryer" },
  { brand: "DENVER", category: "Hair Mask" },
  { brand: "DERMA COLOR", category: "Hair Oil" },
  { brand: "DERMADEW", category: "Hair Pack" },
  { brand: "DERMATOUCH", category: "Hair Remover" },
  { brand: "DERMAVIVE", category: "Hair Roller" },
  { brand: "DERMDOC", category: "Hair Serum" },
  { brand: "DERMI COOL", category: "Hair Spa" },
  { brand: "DERMICOVER", category: "Hair Spray" },
  { brand: "DETTOL", category: "Hair Straightener" },
  { brand: "DF", category: "Hair Towel" },
  { brand: "DOT & KEY", category: "Hair Wax" },
  { brand: "DOVE", category: "Hand Bag" },
  { brand: "DR REDDY", category: "Hand Gloves" },
  { brand: "DR SCHOLLS", category: "Hand Wash" },
  { brand: "DR.ORTHO", category: "Handkerchief" },
  { brand: "DR.RASHEL", category: "Health" },
  { brand: "DR.REDDYS", category: "Heat Powder" },
  { brand: "DR.SHETHS", category: "Henna" },
  { brand: "DURACELL", category: "Highlighter" },
  { brand: "ECOPATH", category: "Inner Wear" },
  { brand: "EMAMI", category: "Intimate Wash" },
  { brand: "ENCHANTEUR", category: "Kajal" },
  { brand: "ENGAGE", category: "Knife" },
  { brand: "ENVY", category: "Lip Balm" },
  { brand: "EVA", category: "Lip Liner" },
  { brand: "EVEREADY", category: "Lip Scrub" },
  { brand: "EVERYUTH", category: "Lipstick" },
  { brand: "EYETAX", category: "Loofah" },
  { brand: "FACES", category: "Makeup Kit" },
  { brand: "FAIR AND LOVELY", category: "Makeup Acc" },
  { brand: "FANCY ITEM", category: "Makeup Brush" },
  { brand: "FEELINGS", category: "Makeup Fixer" },
  { brand: "FEM", category: "Makeup Remover" },
  { brand: "FIAMA", category: "Mascara" },
  { brand: "FIGARO", category: "Mask" },
  { brand: "FIX DERMA", category: "Massager" },
  { brand: "FLORL NUTRITION", category: "Maybelline" },
  { brand: "FLOWEROM", category: "Mehandi Cone" },
  { brand: "FOGG", category: "Mirror" },
  { brand: "FOREST", category: "Mixing Plate" },
  { brand: "FOREVER", category: "Mku01" },
  { brand: "FOREVER52", category: "Moisturizer" },
  { brand: "FOXTALE", category: "Mosquto Repellent" },
  { brand: "GAIATOP", category: "Mouth Spray / Wash" },
  { brand: "GATSBY", category: "Nail Cutter" },
  { brand: "GEOFRESH", category: "Nail Filer" },
  { brand: "GILLETTE", category: "Nail Polish" },
  { brand: "GLAM FAM", category: "Nail Remover" },
  { brand: "GLAM-UP", category: "Neutralizer" },
  { brand: "GLOW & HANDSOME", category: "Nose Strips" },
  { brand: "GODREJ", category: "Oil" },
  { brand: "GOOD VIBES", category: "Olive Oil" },
  { brand: "GOREE", category: "Pain Balm" },
  { brand: "GREEN LEAF", category: "Pedi/Mani Kit" },
  { brand: "GUBB", category: "Pedi/Mani Tool" },
  { brand: "HAIR & CARE", category: "Pedi/Mani Kit" },
  { brand: "HAIR ACC -AARAV", category: "Pedi/Mani Tool" },
  { brand: "HAIR COMB", category: "Perfume" },
  { brand: "HAIR WAX", category: "Pollution Mask" },
  { brand: "HAIRLINE", category: "Powder" },
  { brand: "HAMAM", category: "Powder Puff" },
  { brand: "HAMDARD", category: "Primer" },
  { brand: "HARPIC", category: "Pumice Stone" },
  { brand: "HEAD & SHOULDER", category: "Razor" },
  { brand: "HIMALAYA", category: "Rose Water" },
  { brand: "HIMGANGE", category: "Sanitary" },
  { brand: "HONEYBEE", category: "Sanitary Napkin" },
  { brand: "HYPHEN", category: "Sanitizer" },
  { brand: "ICE ROLLER", category: "Scissor" },
  { brand: "ICE TEMPERED", category: "Scrub" },
  { brand: "IKI", category: "Serum" },
  { brand: "IKONIC", category: "Shampoo" },
  { brand: "INDULEKHA", category: "Sharpener" },
  { brand: "INDUS VALLEY", category: "Shave" },
  { brand: "INSIGHT", category: "Shave Cream" },
  { brand: "JOHNSONS", category: "Shaving Brush" },
  { brand: "JOVEES", category: "Sheet Mask" },
  { brand: "JOY", category: "Shower Cap" },
  { brand: "JOYO", category: "Shower Gel" },
  { brand: "JUICY CHEMISTRY", category: "Sindoor" },
  { brand: "JUST HERBS", category: "Skin Oil" },
  { brand: "KAI", category: "Smooth" },
  { brand: "KAMA AYURVEDA", category: "Soap" },
  { brand: "KANGARO", category: "Socks" },
  { brand: "KARA", category: "Sponge" },
  { brand: "KAY BEAUTY", category: "Spray Applicator" },
  { brand: "KERRATO", category: "Stapler" },
  { brand: "KHADI", category: "Sunscreen" },
  { brand: "KOHE", category: "Sweat Pads" },
  { brand: "KOZICARE", category: "Talcum Powder" },
  { brand: "KRYOLAN", category: "Tissue" },
  { brand: "KTEIN", category: "Toner" },
  { brand: "LA ORGANO", category: "Tongue Cleaner" },
  { brand: "LA SHIELD", category: "Tooth Brush" },
  { brand: "LACTO CALAMINE", category: "Tooth Paste" },
  { brand: "LAKME", category: "Tooth Picks" },
  { brand: "LAKME-SIMPLE", category: "Toothbrush" },
  { brand: "LANEIGE", category: "Toothpick" },
  { brand: "LASER", category: "Trimmer" },
  { brand: "LAYERR", category: "Tweezer" },
  { brand: "LIA", category: "Wax Strips" },
  { brand: "LIFEBUOY", category: "Wipes" }
];

// Complete 364 Brands List
const ALL_BRANDS = [
  "AGARO", "AIR KARPURE", "AIR WICK", "AJAY", "AJMAL", "ALPS GOODNESS", "ALTON", "AMBI PUR",
  "ANIMATE", "ANOOS", "AQUALOGICA", "ARATA", "ARMAF", "AROMA CARE", "AROMA MAGIC", "ASWINI",
  "AUREANA", "AURIC", "AVEENO", "AXE", "AYOUTH VEDA", "AYUR", "BABILA", "BADZ PLAY",
  "BAJAJ", "BANJARA", "BATH & BODY WORKS", "BATISTE", "BBLUNT", "BE BODYWISE", "BEARDO",
  "BEAUTE BLANC", "BEAUTE SECRETS", "BEAUTY", "BEAUTY ZONE", "BELLA VITA ORGANIC",
  "BEURER BEAUTY", "BIGEN", "BILUMA", "BIO OIL", "BIODERMA", "BIOTIQUE", "BLUE HEAVEN",
  "BORO PLUS", "BOROLINE", "BRASIL CACAU PRO", "BRUSHMAN", "BRUT", "CAMAY", "CAMPURE",
  "CANDIO", "CARESMITH", "CERAVE", "CETAPHIL", "CHEMIST AT PLAY", "CHICCO", "CIGAR",
  "CLEAN & CLEAR", "CLEAN AND DRY", "CLEAR", "CLINIC PLUS", "CLOSEUP", "COLGATE",
  "COLOR TREND", "COLORESSENCE", "COSRX", "CURL UP", "CURLIN", "DABUR", "DE CONSTRUCT",
  "DENVER", "DERMA COLOR", "DERMADEW", "DERMATOUCH", "DERMAVIVE", "DERMDOC", "DERMI COOL",
  "DERMICOVER", "DETTOL", "DF", "DOT & KEY", "DOVE", "DR REDDY", "DR SCHOLLS", "DR.ORTHO",
  "DR.RASHEL", "DR.REDDYS", "DR.SHETHS", "DURACELL", "ECOPATH", "EMAMI", "ENCHANTEUR",
  "ENGAGE", "ENVY", "EVA", "EVEREADY", "EVERYUTH", "EYETAX", "FACES", "FAIR AND LOVELY",
  "FANCY ITEM", "FEELINGS", "FEM", "FIAMA", "FIGARO", "FIX DERMA", "FLORL NUTRITION",
  "FLOWEROM", "FOGG", "FOREST", "FOREVER", "FOREVER52", "FOXTALE", "GAIATOP", "GARNIER",
  "GATSBY", "GEOFRESH", "GILLETTE", "GLAM FAM", "GLAM-UP", "GLOW & HANDSOME", "GODREJ",
  "GOOD VIBES", "GOREE", "GREEN LEAF", "GUBB", "HAIR & CARE", "HAIR ACC -AARAV",
  "HAIR COMB", "HAIR WAX", "HAIRLINE", "HAMAM", "HAMDARD", "HARPIC", "HEAD & SHOULDER",
  "HIMALAYA", "HIMGANGE", "HONEYBEE", "HYPHEN", "ICE ROLLER", "ICE TEMPERED", "IKI",
  "IKONIC", "INDULEKHA", "INDUS VALLEY", "INSIGHT", "JOHNSONS", "JOVEES", "JOY", "JOYO",
  "JUICY CHEMISTRY", "JUST HERBS", "KAI", "KAMA AYURVEDA", "KANGARO", "KARA", "KAY BEAUTY",
  "KERRATO", "KHADI", "KOHE", "KOZICARE", "KRYOLAN", "KTEIN", "LA ORGANO", "LA SHIELD",
  "LACTO CALAMINE", "LAKME", "LAKME-SIMPLE", "LANEIGE", "LASER", "LAYERR", "LIA",
  "LIFEBUOY", "LIP BALM", "LIRIL", "LISTERINE", "LIVON", "LOREAL COSMETICS", "LOREAL PRO",
  "LOREAL SKIN CARE", "LOTUS BOTANICALS", "LOTUS HERBALS", "LOTUS ORGANICS", "LOTUS PRO",
  "LOVE BEAUTY AND PLANET", "LUX", "LUXLISS", "M CAFFEINE", "MAKEOVER PROFESSIONAL",
  "MAMA EARTH", "MAN MATTERS", "MARS", "MATRIX", "MAYBELLINE", "MEDIKER", "MEDIMIX",
  "MEERA", "MINIMALIST", "MIRABELLE", "MISS CLAIRE", "MOISTURISER", "MOODS", "MOODY",
  "MOROCCANOIL", "MUNIX", "MYGLAMM", "MYSORE SANDAL", "NANDINI", "NAT HABIT", "NATURES",
  "NAVRATNA", "NEETA", "NEUD", "NEUTRIDERM", "NEUTROGENA", "Nippo", "NISHA", "NIVEA",
  "NUTRIGOW", "NYKAA", "NYLE", "O3+", "ODONIL", "OLAY", "OLD SPICE", "ORAL-B",
  "ORGANIC HARVEST", "ORGANIX MANTRA", "ORIGAMI", "OSHEA", "OSSUM", "OTTO", "OXYGLOW",
  "OXYLIFE", "OZIVA", "OZONE", "PAIN BALM", "PALMERS", "PALMOLIVE", "PAMPERS", "PANTENE",
  "PARACHUTE", "PARK AVENUE", "PARODONTAX", "PASSION INDULGE", "PATANJALI", "PEARS",
  "PEE SAFE", "PEPSODENT", "PHILIPS", "PIGEON", "PILGRIM", "PLIX", "PLUM", "PONDS",
  "POUR HOME", "PRC HERBAL", "PREM DULHAN", "PREMIER", "PREMIUM", "PRIMER", "QOD",
  "QUENCH", "RAAGA", "RAMSONS", "REEQUIL", "REGULARS", "RENEE", "REVLON", "Rexona",
  "RICA", "RICHFEEL", "RIN", "RIYA", "ROOTS", "ROYAL GOLD", "SANFE", "SANTOOR", "SARA",
  "SATURN", "SAVLON", "SCALPE PRO", "SCARLET", "SCHWARZKOPF", "SEBAMED", "SENSODYNE",
  "SESA", "SET WET", "SHAHNAZ HUSAIN", "SHINGAR", "SIMPLE", "SIRONA", "SKIN FX",
  "SLEEK", "SOFTSENS", "SOFY", "SOTRUE", "SOULFLOWER", "SPINZ", "SPRAYMINTT", "SRI KOMAL",
  "ST.BOTANICA", "ST.IVES", "STAG BRAND", "STAG CLUB", "STAYFREE", "STREAX", "SUGAR",
  "SUNCROS", "SUNSCOOP", "SUNSILK", "SUNSTOP GOLD", "SURGICOM", "SWASTIK", "SWISS BEAUTY",
  "TEDIBAR", "TESTER-MAYBELLINE", "THE BODY SHOP", "THE DERMA CO", "THE FACE SHOP",
  "THE MAN COMPANY", "THE MOMS CO.", "THE TRIBE CONCEPTS", "THRICECO", "TMS NCP",
  "TMS NCP1", "TORRENT", "TRESEMME", "TRICHUP", "TRITON", "TRU TONE", "TRYCONE",
  "TULIPS", "UNITED COLORS OF BENETTON", "URBAN BOTANICS", "URBAN GABRU", "URBAN YOG",
  "URBANVEDA COMP", "UROPARIS PROFESSIONAL", "USTRAA", "UV DOUX", "V WASH", "VAADI HERBALS",
  "VANESA", "VASELINE", "VCARE", "VEET", "VEGA", "VICCO", "VICKS", "VI-JOHN", "VILLAIN",
  "VINZBERRY", "VLCC", "WA JAPAN", "WATTAGIRL", "WELLA", "WHISPER", "WHITETONE",
  "WILD STONE", "WISHCARE", "WOW", "YARDLEY", "Z CLASSIC", "ZANDU"
];

const DEFAULT_LOGO = 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=300&auto=format&fit=crop&q=80';

// Preset category icons for visual appeal
const CATEGORY_ICON_MAP = {
  "After Shave": "💈",
  "Air Freshner": "🍃",
  "Almond Oil": "🧴",
  "Aloevera Gel": "🌿",
  "Antiseptic Liquid": "🩹",
  "Bath Brush": "🧼",
  "Bath Powder": "✨",
  "Bath Salt": "🧂",
  "Battery": "🔋",
  "BB Cream": "💄",
  "Bindi": "🔴",
  "Blackhead Remover": "✨",
  "Blusher": "🌸",
  "Body Lotion": "🧴",
  "Body Scrub": "🛁",
  "Body Spray": "💨",
  "Body Wash": "🚿",
  "Body Wax": "🍯",
  "Bottle": "🍼",
  "Brush": "🖌️",
  "Brush Cleaner": "🧼",
  "Cartridge": "🪒",
  "Castor Oil": "🛢️",
  "Cleaner Flr / Toilt": "🧹",
  "Cleansing Milk": "🧴",
  "Compact": "🪞",
  "Concealer": "✨",
  "Conditioner": "💇‍♀️",
  "Cotton": "☁️",
  "Cotton Pads": "☁️",
  "Cream": "🧴",
  "Deodrant": "💨",
  "Derma Roller": "💆‍♀️",
  "Developer": "🧪",
  "Diapers": "👶",
  "Ear Buds": "👂",
  "Ear Plug": "🔇",
  "Ear Ring": "💎",
  "Essential": "🌿",
  "Essential Oil": "💧",
  "Eye Lash": "👁️",
  "Eye Lash Glue": "👁️",
  "Eye Shadow": "🎨",
  "Eyebrow": "✏️",
  "Eyebrow Pencil": "✏️",
  "Eyelash Curler": "👁️",
  "Eyeliner": "🖋️",
  "Eyeshadow": "🎨",
  "Face Cream": "🧴",
  "Face Mask": "🎭",
  "Face Mist": "💦",
  "Face Pack": "🧖‍♀️",
  "Face Scrub": "🧼",
  "Face Serum": "💧",
  "Face Wash": "🧼",
  "Facial Band": "🎀",
  "Facial Kit": "💆‍♀️",
  "Fancy Item": "🎁",
  "Foot Filer": "🦶",
  "Foundation": "💄",
  "Freshner": "🌸",
  "General Item": "🛍️",
  "Grooming": "✂️",
  "Hair Acc": "🎀",
  "Hair Brush": "💇‍♀️",
  "Hair Color": "🎨",
  "Hair Comb": "💇‍♀️",
  "Hair Cream": "🧴",
  "Hair Dryer": "💨",
  "Hair Mask": "💆‍♀️",
  "Hair Oil": "🛢️",
  "Hair Pack": "🌿",
  "Hair Remover": "🪒",
  "Hair Roller": "👩‍🦱",
  "Hair Serum": "💧",
  "Hair Spa": "🧖‍♀️",
  "Hair Spray": "💨",
  "Hair Straightener": "🔌",
  "Hair Towel": "🧖‍♀️",
  "Hair Wax": "💇‍♂️",
  "Hand Bag": "👜",
  "Hand Gloves": "🧤",
  "Hand Wash": "🧼",
  "Handkerchief": "🧣",
  "Health": "💊",
  "Heat Powder": "☀️",
  "Henna": "🌿",
  "Highlighter": "✨",
  "Inner Wear": "🩲",
  "Intimate Wash": "🧼",
  "Kajal": "🖊️",
  "Knife": "🔪",
  "Lip Balm": "💄",
  "Lip Liner": "✏️",
  "Lip Scrub": "👄",
  "Lipstick": "💄",
  "Loofah": "🧽",
  "Makeup Kit": "🧰",
  "Makeup Acc": "💅",
  "Makeup Brush": "🖌️",
  "Makeup Fixer": "💦",
  "Makeup Remover": "🧴",
  "Mascara": "👁️",
  "Mask": "😷",
  "Massager": "💆‍♂️",
  "Maybelline": "💄",
  "Mehandi Cone": "🌿",
  "Mirror": "🪞",
  "Mixing Plate": "🎨",
  "Mku01": "💅",
  "Moisturizer": "🧴",
  "Mosquto Repellent": "🦟",
  "Mouth Spray / Wash": "👄",
  "Nail Cutter": "✂️",
  "Nail Filer": "💅",
  "Nail Polish": "💅",
  "Nail Remover": "💧",
  "Neutralizer": "🧪",
  "Nose Strips": "👃",
  "Oil": "🛢️",
  "Olive Oil": "🫒",
  "Pain Balm": "🩹",
  "Pedi/Mani Kit": "💅",
  "Pedi/Mani Tool": "🛠️",
  "Perfume": "🧴",
  "Pollution Mask": "😷",
  "Powder": "✨",
  "Powder Puff": "☁️",
  "Primer": "✨",
  "Pumice Stone": "🪨",
  "Razor": "🪒",
  "Rose Water": "🌹",
  "Sanitary": "🩸",
  "Sanitary Napkin": "🩸",
  "Sanitizer": "🧴",
  "Scissor": "✂️",
  "Scrub": "🧼",
  "Serum": "💧",
  "Shampoo": "🧴",
  "Sharpener": "✏️",
  "Shave": "🪒",
  "Shave Cream": "🪒",
  "Shaving Brush": "🖌️",
  "Sheet Mask": "🧖‍♀️",
  "Shower Cap": "🛁",
  "Shower Gel": "🚿",
  "Sindoor": "🔴",
  "Skin Oil": "💧",
  "Smooth": "✨",
  "Soap": "🧼",
  "Socks": "🧦",
  "Sponge": "🧽",
  "Spray Applicator": "💨",
  "Stapler": "📎",
  "Sunscreen": "☀️",
  "Sweat Pads": "💧",
  "Talcum Powder": "✨",
  "Tissue": "🧻",
  "Toner": "💦",
  "Tongue Cleaner": "👅",
  "Tooth Brush": "🪥",
  "Tooth Paste": "🪥",
  "Tooth Picks": "🥢",
  "Toothbrush": "🪥",
  "Toothpick": "🥢",
  "Trimmer": "✂️",
  "Tweezer": "📍",
  "Wax Strips": "🍯",
  "Wipes": "🧻"
};

async function seedCategoriesAndBrands() {
  console.log('Processing Brand & Category Dataset...');

  // Build brand-to-category dictionary
  const brandToCategoryMap = {};
  MAPPED_ROWS.forEach(row => {
    brandToCategoryMap[row.brand] = row.category;
  });

  // Unique categories list
  const uniqueCategoryNames = Array.from(new Set(MAPPED_ROWS.map(r => r.category)));
  console.log(`Found ${uniqueCategoryNames.length} Unique Category Items.`);

  // Build category objects
  const categoryRows = uniqueCategoryNames.map((catName, idx) => ({
    id: 'cat_' + (idx + 1),
    name: catName,
    icon: CATEGORY_ICON_MAP[catName] || '🛍️',
    image: `https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=300&auto=format&fit=crop&q=80`,
    color: '#FCE4EC',
    sort_order: idx + 1,
    enabled: true
  }));

  // 1. Seed categories table & app_category_order_config row in brands table
  console.log('Seeding categories into Supabase categories table...');
  const { error: catErr } = await supabase.from('categories').upsert(categoryRows);
  if (catErr) console.warn('Categories table upsert notice:', catErr.message);

  // Sync category config into brands table for mobile fallback
  console.log('Syncing app_category_order_config into Supabase brands table...');
  await supabase.from('brands').upsert({
    id: 'app_category_order_config',
    name: 'Category Order Config',
    logo: JSON.stringify(categoryRows),
    enabled: true
  });

  // Sync brand to category mapping dictionary into brands table
  console.log('Syncing app_brand_category_map into Supabase brands table...');
  await supabase.from('brands').upsert({
    id: 'app_brand_category_map',
    name: 'Brand Category Mapping',
    logo: JSON.stringify(brandToCategoryMap),
    enabled: true
  });

  // 2. Build full 364 brand rows
  console.log(`Updating ${ALL_BRANDS.length} Brand records...`);
  const brandRows = ALL_BRANDS.map((brandName, idx) => {
    return {
      id: 'b_' + (idx + 1),
      name: brandName,
      enabled: true,
      logo: DEFAULT_LOGO
    };
  });

  const chunkSize = 50;
  for (let i = 0; i < brandRows.length; i += chunkSize) {
    const chunk = brandRows.slice(i, i + chunkSize);
    const { error } = await supabase.from('brands').upsert(chunk);
    if (error) {
      console.error(`Brand chunk ${i / chunkSize + 1} error:`, error.message);
    } else {
      console.log(`Seeded brand chunk ${i / chunkSize + 1} (${chunk.length} brands)`);
    }
  }

  console.log('All Brand & Category dataset seeded successfully!');
}

seedCategoriesAndBrands();
